env:
  es2021: true
  node: true
  es6: true
  camelcase: true
  no-console: warn
  import/extensions:
  - error
  - ignorePackages
  - js: never
    mjs: never
    jsx: never
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
